apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: microservices
spec:
  ports:
    - port: 6379
      protocol: TCP # default
      name: redis # optional when only 1 port
  selector:
    tier: data
  type: ClusterIP # default
---
apiVersion: v1
kind: Pod
metadata:
  name: data-tier
  labels:
    app: microservices
    tier: data
spec:
  containers:
    - name: redis
      image: redis:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "128Mi" # 128Mi = 128 mebibytes
          cpu: "500m" # 500m = 500 milliCPUs (1/2 CPU)
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379
